In [1]:
import pandas as pd

In [2]:
data=pd.read_excel("sales.xlsx")

In [3]:
data

       name  age       city          state  product  price
0      neha   23      noida  uttar pradesh   iphone  20000
1    deepak   45      delhi          delhi   iphone  30000
2       raj   67      delhi          delhi  samsung  45000
3    suresh   78      delhi          delhi   iphone  56000
4    himesh   32      noida  uttar pradesh  samsung  78000
5  dharmesh   45       pune    maharashtra    nokia   4567
6    puneet   32  rajasthan      rajasthan  samsung   4334
7   vishant   45       pune    maharashtra     oppo   2344

In [7]:
result = data.groupby('product').agg(
    newcol=('price','sum')
)

result = result.reset_index()
result

   product  newcol
0   iphone  106000
1    nokia    4567
2     oppo    2344
3  samsung  127334

In [9]:
result = data.groupby(['state','product']).agg(
    newcol=('price','sum')
)
result = result.reset_index()
result

           state  product  newcol
0          delhi   iphone   86000
1          delhi  samsung   45000
2    maharashtra    nokia    4567
3    maharashtra     oppo    2344
4      rajasthan  samsung    4334
5  uttar pradesh   iphone   20000
6  uttar pradesh  samsung   78000